version: "3.8"

services:
  # osrm-server service removed

  osrm-data-processor:
    build:
      context: ./osrm-data-processor
      dockerfile: Dockerfile
    container_name: osrm-data-processor
    ports:
      - "5002:5000" # OSRM default port, mapped to 5002 on host to avoid conflict
    volumes:
      - ./osrm-data:/osrm-data
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    container_name: backend
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    volumes:
      - ./src/backend:/app/backend
      - ./src/database:/app/database
      - ./src/model:/app/model
      - ./data:/data
      - ./src/main.py:/app/main.py
    depends_on:
      - osrm-data-processor
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./src/frontend/map
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
      - osrm-data-processor
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
